server:
  port: 9501
spring:
  profiles:
    active: dev
  application:
    name: oauth2-resource

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

