server:
  port: 8761
spring:
  profiles:
    active: dev
  application:
    name: eureka-server

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
